import = [
 "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]

[env]
TERM = "xterm-256color"




 

colors = 'gruvbox_material_hard_dark'

[font]
normal.family = "MesloLGS Nerd Font Mono"


